// Auto-generated by Supabase MCP — do not edit manually.
// Regenerate with: pnpm supabase:types
// Last generated: 2026-06-12 (AP-28: mark_email_status RPC applied)

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5";
  };
  public: {
    Tables: {
      app_meta: {
        Row: {
          created_at: string;
          key: string;
          updated_at: string;
          value: string;
        };
        Insert: {
          created_at?: string;
          key: string;
          updated_at?: string;
          value: string;
        };
        Update: {
          created_at?: string;
          key?: string;
          updated_at?: string;
          value?: string;
        };
        Relationships: [];
      };
      business_members: {
        Row: {
          business_id: string;
          role: string;
          user_id: string;
        };
        Insert: {
          business_id: string;
          role?: string;
          user_id: string;
        };
        Update: {
          business_id?: string;
          role?: string;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "business_members_business_id_fkey";
            columns: ["business_id"];
            isOneToOne: false;
            referencedRelation: "businesses";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "business_members_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      businesses: {
        Row: {
          address: string | null;
          created_at: string;
          currency: string;
          default_gst_rate: number | null;
          gst_enabled: boolean;
          gstin: string | null;
          id: string;
          invoice_prefix: string;
          logo_url: string | null;
          name: string;
          owner_id: string;
          plan: string;
          state_code: string | null;
          upi_id: string | null;
        };
        Insert: {
          address?: string | null;
          created_at?: string;
          currency?: string;
          default_gst_rate?: number | null;
          gst_enabled?: boolean;
          gstin?: string | null;
          id?: string;
          invoice_prefix?: string;
          logo_url?: string | null;
          name: string;
          owner_id: string;
          plan?: string;
          state_code?: string | null;
          upi_id?: string | null;
        };
        Update: {
          address?: string | null;
          created_at?: string;
          currency?: string;
          default_gst_rate?: number | null;
          gst_enabled?: boolean;
          gstin?: string | null;
          id?: string;
          invoice_prefix?: string;
          logo_url?: string | null;
          name?: string;
          owner_id?: string;
          plan?: string;
          state_code?: string | null;
          upi_id?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "businesses_owner_id_fkey";
            columns: ["owner_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      customers: {
        Row: {
          billing_address: string | null;
          business_id: string;
          city: string | null;
          created_at: string | null;
          email: string | null;
          gstin: string | null;
          id: string;
          name: string;
          notes: string | null;
          opening_balance: number;
          phone: string | null;
          state_code: string | null;
        };
        Insert: {
          billing_address?: string | null;
          business_id: string;
          city?: string | null;
          created_at?: string | null;
          email?: string | null;
          gstin?: string | null;
          id?: string;
          name: string;
          notes?: string | null;
          opening_balance?: number;
          phone?: string | null;
          state_code?: string | null;
        };
        Update: {
          billing_address?: string | null;
          business_id?: string;
          city?: string | null;
          created_at?: string | null;
          email?: string | null;
          gstin?: string | null;
          id?: string;
          name?: string;
          notes?: string | null;
          opening_balance?: number;
          phone?: string | null;
          state_code?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "customers_business_id_fkey";
            columns: ["business_id"];
            isOneToOne: false;
            referencedRelation: "businesses";
            referencedColumns: ["id"];
          },
        ];
      };
      invoice_events: {
        Row: {
          business_id: string;
          channel: string | null;
          created_at: string | null;
          id: string;
          invoice_id: string | null;
          meta: Json | null;
          type: string;
        };
        Insert: {
          business_id: string;
          channel?: string | null;
          created_at?: string | null;
          id?: string;
          invoice_id?: string | null;
          meta?: Json | null;
          type: string;
        };
        Update: {
          business_id?: string;
          channel?: string | null;
          created_at?: string | null;
          id?: string;
          invoice_id?: string | null;
          meta?: Json | null;
          type?: string;
        };
        Relationships: [
          {
            foreignKeyName: "invoice_events_business_id_fkey";
            columns: ["business_id"];
            isOneToOne: false;
            referencedRelation: "businesses";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "invoice_events_invoice_id_fkey";
            columns: ["invoice_id"];
            isOneToOne: false;
            referencedRelation: "invoices";
            referencedColumns: ["id"];
          },
        ];
      };
      invoice_line_items: {
        Row: {
          cgst: number;
          discount: number;
          gst_rate: number;
          hsn_sac: string | null;
          id: string;
          igst: number;
          invoice_id: string;
          line_subtotal: number;
          line_tax: number;
          line_total: number;
          name: string;
          position: number;
          qty: number;
          sgst: number;
          unit_price: number;
        };
        Insert: {
          cgst?: number;
          discount?: number;
          gst_rate?: number;
          hsn_sac?: string | null;
          id?: string;
          igst?: number;
          invoice_id: string;
          line_subtotal?: number;
          line_tax?: number;
          line_total?: number;
          name: string;
          position?: number;
          qty?: number;
          sgst?: number;
          unit_price?: number;
        };
        Update: {
          cgst?: number;
          discount?: number;
          gst_rate?: number;
          hsn_sac?: string | null;
          id?: string;
          igst?: number;
          invoice_id?: string;
          line_subtotal?: number;
          line_tax?: number;
          line_total?: number;
          name?: string;
          position?: number;
          qty?: number;
          sgst?: number;
          unit_price?: number;
        };
        Relationships: [
          {
            foreignKeyName: "invoice_line_items_invoice_id_fkey";
            columns: ["invoice_id"];
            isOneToOne: false;
            referencedRelation: "invoices";
            referencedColumns: ["id"];
          },
        ];
      };
      invoice_sequences: {
        Row: {
          business_id: string;
          fy: string;
          last_number: number;
        };
        Insert: {
          business_id: string;
          fy: string;
          last_number?: number;
        };
        Update: {
          business_id?: string;
          fy?: string;
          last_number?: number;
        };
        Relationships: [
          {
            foreignKeyName: "invoice_sequences_business_id_fkey";
            columns: ["business_id"];
            isOneToOne: false;
            referencedRelation: "businesses";
            referencedColumns: ["id"];
          },
        ];
      };
      invoices: {
        Row: {
          amount_paid: number;
          business_id: string;
          cgst: number;
          created_at: string | null;
          created_by: string | null;
          customer_id: string | null;
          discount: number;
          due_date: string | null;
          gst_enabled: boolean;
          id: string;
          igst: number;
          is_interstate: boolean;
          issue_date: string;
          notes: string | null;
          number: string | null;
          paid_at: string | null;
          pdf_url: string | null;
          place_of_supply: string | null;
          public_token: string | null;
          round_off: number;
          sent_at: string | null;
          sgst: number;
          status: Database["public"]["Enums"]["invoice_status"];
          subtotal: number;
          tax_total: number;
          terms: string | null;
          total: number;
          updated_at: string | null;
          viewed_at: string | null;
        };
        Insert: {
          amount_paid?: number;
          business_id: string;
          cgst?: number;
          created_at?: string | null;
          created_by?: string | null;
          customer_id?: string | null;
          discount?: number;
          due_date?: string | null;
          gst_enabled?: boolean;
          id?: string;
          igst?: number;
          is_interstate?: boolean;
          issue_date?: string;
          notes?: string | null;
          number?: string | null;
          paid_at?: string | null;
          pdf_url?: string | null;
          place_of_supply?: string | null;
          public_token?: string | null;
          round_off?: number;
          sent_at?: string | null;
          sgst?: number;
          status?: Database["public"]["Enums"]["invoice_status"];
          subtotal?: number;
          tax_total?: number;
          terms?: string | null;
          total?: number;
          updated_at?: string | null;
          viewed_at?: string | null;
        };
        Update: {
          amount_paid?: number;
          business_id?: string;
          cgst?: number;
          created_at?: string | null;
          created_by?: string | null;
          customer_id?: string | null;
          discount?: number;
          due_date?: string | null;
          gst_enabled?: boolean;
          id?: string;
          igst?: number;
          is_interstate?: boolean;
          issue_date?: string;
          notes?: string | null;
          number?: string | null;
          paid_at?: string | null;
          pdf_url?: string | null;
          place_of_supply?: string | null;
          public_token?: string | null;
          round_off?: number;
          sent_at?: string | null;
          sgst?: number;
          status?: Database["public"]["Enums"]["invoice_status"];
          subtotal?: number;
          tax_total?: number;
          terms?: string | null;
          total?: number;
          updated_at?: string | null;
          viewed_at?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "invoices_business_id_fkey";
            columns: ["business_id"];
            isOneToOne: false;
            referencedRelation: "businesses";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "invoices_created_by_fkey";
            columns: ["created_by"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "invoices_customer_id_fkey";
            columns: ["customer_id"];
            isOneToOne: false;
            referencedRelation: "customers";
            referencedColumns: ["id"];
          },
        ];
      };
      items: {
        Row: {
          business_id: string;
          created_at: string | null;
          default_gst_rate: number | null;
          default_price: number | null;
          hsn_sac: string | null;
          id: string;
          name: string;
          unit: string | null;
        };
        Insert: {
          business_id: string;
          created_at?: string | null;
          default_gst_rate?: number | null;
          default_price?: number | null;
          hsn_sac?: string | null;
          id?: string;
          name: string;
          unit?: string | null;
        };
        Update: {
          business_id?: string;
          created_at?: string | null;
          default_gst_rate?: number | null;
          default_price?: number | null;
          hsn_sac?: string | null;
          id?: string;
          name?: string;
          unit?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "items_business_id_fkey";
            columns: ["business_id"];
            isOneToOne: false;
            referencedRelation: "businesses";
            referencedColumns: ["id"];
          },
        ];
      };
      message_log: {
        Row: {
          business_id: string;
          channel: string;
          created_at: string | null;
          error: string | null;
          id: string;
          invoice_id: string | null;
          provider_msg_id: string | null;
          status: string;
          updated_at: string | null;
        };
        Insert: {
          business_id: string;
          channel: string;
          created_at?: string | null;
          error?: string | null;
          id?: string;
          invoice_id?: string | null;
          provider_msg_id?: string | null;
          status?: string;
          updated_at?: string | null;
        };
        Update: {
          business_id?: string;
          channel?: string;
          created_at?: string | null;
          error?: string | null;
          id?: string;
          invoice_id?: string | null;
          provider_msg_id?: string | null;
          status?: string;
          updated_at?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "message_log_business_id_fkey";
            columns: ["business_id"];
            isOneToOne: false;
            referencedRelation: "businesses";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "message_log_invoice_id_fkey";
            columns: ["invoice_id"];
            isOneToOne: false;
            referencedRelation: "invoices";
            referencedColumns: ["id"];
          },
        ];
      };
      notifications: {
        Row: {
          body: string | null;
          business_id: string;
          created_at: string | null;
          id: string;
          link: string | null;
          read: boolean;
          title: string | null;
          type: string;
          user_id: string | null;
        };
        Insert: {
          body?: string | null;
          business_id: string;
          created_at?: string | null;
          id?: string;
          link?: string | null;
          read?: boolean;
          title?: string | null;
          type: string;
          user_id?: string | null;
        };
        Update: {
          body?: string | null;
          business_id?: string;
          created_at?: string | null;
          id?: string;
          link?: string | null;
          read?: boolean;
          title?: string | null;
          type?: string;
          user_id?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "notifications_business_id_fkey";
            columns: ["business_id"];
            isOneToOne: false;
            referencedRelation: "businesses";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "notifications_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      payments: {
        Row: {
          amount: number;
          business_id: string;
          id: string;
          invoice_id: string;
          method: string;
          note: string | null;
          paid_at: string | null;
          provider_ref: string | null;
          recorded_by: string | null;
          reference: string | null;
        };
        Insert: {
          amount: number;
          business_id: string;
          id?: string;
          invoice_id: string;
          method?: string;
          note?: string | null;
          paid_at?: string | null;
          provider_ref?: string | null;
          recorded_by?: string | null;
          reference?: string | null;
        };
        Update: {
          amount?: number;
          business_id?: string;
          id?: string;
          invoice_id?: string;
          method?: string;
          note?: string | null;
          paid_at?: string | null;
          provider_ref?: string | null;
          recorded_by?: string | null;
          reference?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "payments_business_id_fkey";
            columns: ["business_id"];
            isOneToOne: false;
            referencedRelation: "businesses";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "payments_invoice_id_fkey";
            columns: ["invoice_id"];
            isOneToOne: false;
            referencedRelation: "invoices";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "payments_recorded_by_fkey";
            columns: ["recorded_by"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      profiles: {
        Row: {
          created_at: string;
          display_name: string | null;
          id: string;
          language: string;
          phone: string;
        };
        Insert: {
          created_at?: string;
          display_name?: string | null;
          id: string;
          language?: string;
          phone: string;
        };
        Update: {
          created_at?: string;
          display_name?: string | null;
          id?: string;
          language?: string;
          phone?: string;
        };
        Relationships: [];
      };
      reminder_rules: {
        Row: {
          business_id: string;
          channel: string;
          enabled: boolean;
          offsets_days: number[];
        };
        Insert: {
          business_id: string;
          channel?: string;
          enabled?: boolean;
          offsets_days?: number[];
        };
        Update: {
          business_id?: string;
          channel?: string;
          enabled?: boolean;
          offsets_days?: number[];
        };
        Relationships: [
          {
            foreignKeyName: "reminder_rules_business_id_fkey";
            columns: ["business_id"];
            isOneToOne: true;
            referencedRelation: "businesses";
            referencedColumns: ["id"];
          },
        ];
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      cancel_invoice: {
        Args: { p_business_id: string; p_invoice_id: string };
        Returns: Json;
      };
      create_business: {
        Args: {
          p_address: string;
          p_gstin: string;
          p_name: string;
          p_state_code: string;
          p_upi_id: string;
        };
        Returns: string;
      };
      delete_invoice: {
        Args: { p_business_id: string; p_invoice_id: string };
        Returns: Json;
      };
      delete_item: {
        Args: { p_business_id: string; p_item_id: string };
        Returns: undefined;
      };
      duplicate_invoice: {
        Args: { p_business_id: string; p_invoice_id: string };
        Returns: Json;
      };
      get_public_invoice: { Args: { p_token: string }; Returns: Json };
      issue_invoice: {
        Args: { p_business_id: string; p_invoice_id: string };
        Returns: Json;
      };
      list_items: {
        Args: { p_business_id: string; p_limit?: number };
        Returns: Json;
      };
      mark_email_status: {
        Args: { p_provider_msg_id: string; p_status: string };
        Returns: Json;
      };
      mark_invoice_paid: {
        Args: { p_business_id: string; p_invoice_id: string; p_method?: string };
        Returns: Json;
      };
      mark_message_status: {
        Args: { p_provider_msg_id: string; p_status: string };
        Returns: Json;
      };
      next_invoice_number: {
        Args: { p_business_id: string; p_issue_date?: string };
        Returns: string;
      };
      record_payment: {
        Args: {
          p_amount: number;
          p_business_id: string;
          p_invoice_id: string;
          p_method?: string;
          p_note?: string;
          p_reference?: string;
        };
        Returns: Json;
      };
      save_invoice_draft: {
        Args: {
          p_business_id: string;
          p_cgst?: number;
          p_customer_id?: string;
          p_gst_enabled?: boolean;
          p_igst?: number;
          p_invoice_id?: string;
          p_is_interstate?: boolean;
          p_line_items?: Json;
          p_notes?: string;
          p_round_off?: number;
          p_sgst?: number;
          p_subtotal?: number;
          p_tax_total?: number;
          p_total?: number;
        };
        Returns: Json;
      };
      search_customers: {
        Args: { p_business_id: string; p_limit?: number; p_query: string };
        Returns: Json[];
      };
      sweep_overdue_invoices: { Args: never; Returns: Json };
      upsert_customer: {
        Args: {
          p_billing_address?: string;
          p_business_id: string;
          p_city?: string;
          p_customer_id?: string;
          p_email?: string;
          p_gstin?: string;
          p_name: string;
          p_notes?: string;
          p_phone?: string;
          p_state_code?: string;
        };
        Returns: Json;
      };
      upsert_item: {
        Args: {
          p_business_id: string;
          p_default_gst_rate?: number;
          p_default_price?: number;
          p_hsn_sac?: string;
          p_item_id?: string;
          p_name: string;
          p_unit?: string;
        };
        Returns: Json;
      };
    };
    Enums: {
      invoice_status:
        | "draft"
        | "sent"
        | "viewed"
        | "partial"
        | "pending"
        | "paid"
        | "overdue"
        | "cancelled";
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
};

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">;

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">];

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R;
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] & DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R;
      }
      ? R
      : never
    : never;

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I;
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I;
      }
      ? I
      : never
    : never;

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U;
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U;
      }
      ? U
      : never
    : never;

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never;

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never;

export const Constants = {
  public: {
    Enums: {
      invoice_status: [
        "draft",
        "sent",
        "viewed",
        "partial",
        "pending",
        "paid",
        "overdue",
        "cancelled",
      ],
    },
  },
} as const;
